# Generated by Django 3.2.8 on 2021-10-31 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.TextField()),
                ('passText', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('expired', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 21, 23, 34, 158392), verbose_name='expired')),
            ],
            options={
                'db_table': 'auth',
                'managed': False,
            },
        ),
    ]
