# Generated by Django 3.2.8 on 2021-10-31 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('cliente_usuario_id', models.IntegerField(unique=True)),
                ('cliente_id', models.IntegerField(default=1)),
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('expired', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 18, 42, 40, 935921), verbose_name='expired')),
            ],
            options={
                'db_table': 'base_token',
                'managed': False,
            },
        ),
    ]
