# Generated by Django 3.2.8 on 2021-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_ingreso', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('model', models.TextField()),
                ('patente', models.TextField()),
                ('id_reparacion', models.JSONField()),
                ('id_client', models.IntegerField()),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cliente_usuario_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('perfil_id', models.IntegerField()),
                ('name', models.TextField()),
                ('mail', models.TextField()),
                ('cell', models.IntegerField()),
                ('cars', models.JSONField()),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_car', models.IntegerField()),
                ('description', models.TextField()),
                ('entryDate', models.DateTimeField()),
                ('finalDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'repair',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='token',
            table='token',
        ),
    ]
